server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: cityfix-api
  profiles:
    active: dev

  jackson:
    mapper:
      accept-case-insensitive-enums: true
      accept-case-insensitive-properties: true  # optional, handy

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/cityfix}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:postgres}
    driver-class-name: org.postgresql.Driver

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASS:guest}
    virtual-host: ${RABBITMQ_VHOST:/}
    publisher-confirm-type: correlated   # enables broker confirms
    publisher-returns: true              # enables "returned" callback when unroutable
    template:
      mandatory: true                    # required for returns to fire

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

app:
  security:
    jwt:
      secret: ${JWT_SECRET:dev-secret-please-change-me-0123456789abcdef0123456789abcd}
      expires-in-seconds: ${JWT_EXPIRES:86400}   # 24h

  storage:
    upload-dir: ${FILE_UPLOAD_DIR:${user.home}/cityfix_uploads}
